### ISSUE TITLE
No output when running wav2rtp ver 0.9.3

### ISSUE THREAD

**Issue by bouldertatum** [imankulov/wav2rtp#1]
I was able to compile 0.9.3 with no issues but a few warnings - see output below.  When trying to used wav2rtp I see no output.  I have tried using full paths for input/output but still nothing.

  atatum@webserver1:~/wav2rtp$ pwd
/home/atatum/wav2rtp
atatum@webserver1:~/wav2rtp$ wav2rtp -f /home/atatum/wav2rtp/dream.wav -t /home/atatum/wav2rtp/dream.pcap -c PCMU
atatum@webserver1:~/wav2rtp$ ls
dream.wav
atatum@webserver1:~/wav2rtp$

The following is stdout from configure and  compile via 'make'
root@webserver1:~/wav2rtp/wav2rtp-0.9.3# ./configure LIBS="-lm"
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/root/wav2rtp/wav2rtp-0.9.3/missing: Unknown `--is-lightweight' option
Try`/root/wav2rtp/wav2rtp-0.9.3/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gsm_create in -lgsm... yes
checking for sf_open in -lsndfile... yes
checking for speex_encoder_init in -lspeex... yes
checking for pcap_next in -lpcap... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether time.h and sys/time.h may both be included... yes
checking for uint32_t... yes
checking for uint8_t... yes
checking whether byte ordering is bigendian... no
checking for bzero... yes
checking for gettimeofday... yes
checking for strchr... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating conf/Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands
root@webserver1:~/wav2rtp/wav2rtp-0.9.3# make
make  all-recursive
make[1]: Entering directory '/root/wav2rtp/wav2rtp-0.9.3'
Making all in src
make[2]: Entering directory '/root/wav2rtp/wav2rtp-0.9.3/src'
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT wav2rtp.o -MD -MP -MF .deps/wav2rtp.Tpo -c -o wav2rtp.o wav2rtp.c
wav2rtp.c: In function ‘main’:
wav2rtp.c:98:9: warning: implicit declaration of function ‘setall’ [-Wimplicit-function-declaration]
         setall(random(), random());
         ^
mv -f .deps/wav2rtp.Tpo .deps/wav2rtp.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT rtpmap.o -MD -MP -MF .deps/rtpmap.Tpo -c -o rtpmap.o rtpmap.c
rtpmap.c: In function ‘get_encoder_by_name’:
rtpmap.c:73:13: warning: implicit declaration of function ‘strncmp’ [-Wimplicit-function-declaration]
         if (strncmp(pcodec->name, name, WR_MAX_CODEC_NAME_SIZE) == 0 ){
             ^
mv -f .deps/rtpmap.Tpo .deps/rtpmap.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT options.o -MD -MP -MF .deps/options.Tpo -c -o options.o options.c
mv -f .deps/options.Tpo .deps/options.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT speex_codec.o -MD -MP -MF .deps/speex_codec.Tpo -c -o speex_codec.o speex_codec.c
mv -f .deps/speex_codec.Tpo .deps/speex_codec.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT dummy_codec.o -MD -MP -MF .deps/dummy_codec.Tpo -c -o dummy_codec.o dummy_codec.c
mv -f .deps/dummy_codec.Tpo .deps/dummy_codec.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT gsm_codec.o -MD -MP -MF .deps/gsm_codec.Tpo -c -o gsm_codec.o gsm_codec.c
mv -f .deps/gsm_codec.Tpo .deps/gsm_codec.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT g711u_codec.o -MD -MP -MF .deps/g711u_codec.Tpo -c -o g711u_codec.o g711u_codec.c
mv -f .deps/g711u_codec.Tpo .deps/g711u_codec.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT g711.o -MD -MP -MF .deps/g711.Tpo -c -o g711.o `test -f 'contrib/g711.c' || echo './'`contrib/g711.c
mv -f .deps/g711.Tpo .deps/g711.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT in_cksum.o -MD -MP -MF .deps/in_cksum.Tpo -c -o in_cksum.o `test -f 'contrib/in_cksum.c' || echo './'`contrib/in_cksum.c
contrib/in_cksum.c: In function ‘in_cksum_shouldbe’:
contrib/in_cksum.c:190:14: warning: implicit declaration of function ‘ntohs’ [-Wimplicit-function-declaration]
  shouldbe += ntohs(computed_sum);
              ^
mv -f .deps/in_cksum.Tpo .deps/in_cksum.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT iniparser.o -MD -MP -MF .deps/iniparser.Tpo -c -o iniparser.o `test -f 'contrib/iniparser.c' || echo './'`contrib/iniparser.c
mv -f .deps/iniparser.Tpo .deps/iniparser.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT simclist.o -MD -MP -MF .deps/simclist.Tpo -c -o simclist.o `test -f 'contrib/simclist.c' || echo './'`contrib/simclist.c
mv -f .deps/simclist.Tpo .deps/simclist.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT com.o -MD -MP -MF .deps/com.Tpo -c -o com.o `test -f 'contrib/ranlib/com.c' || echo './'`contrib/ranlib/com.c
mv -f .deps/com.Tpo .deps/com.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT linpack.o -MD -MP -MF .deps/linpack.Tpo -c -o linpack.o `test -f 'contrib/ranlib/linpack.c' || echo './'`contrib/ranlib/linpack.c
mv -f .deps/linpack.Tpo .deps/linpack.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT ranlib.o -MD -MP -MF .deps/ranlib.Tpo -c -o ranlib.o `test -f 'contrib/ranlib/ranlib.c' || echo './'`contrib/ranlib/ranlib.c
mv -f .deps/ranlib.Tpo .deps/ranlib.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT rtpapi.o -MD -MP -MF .deps/rtpapi.Tpo -c -o rtpapi.o rtpapi.c
mv -f .deps/rtpapi.Tpo .deps/rtpapi.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT wavfile_filter.o -MD -MP -MF .deps/wavfile_filter.Tpo -c -o wavfile_filter.o wavfile_filter.c
mv -f .deps/wavfile_filter.Tpo .deps/wavfile_filter.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT pcap_filter.o -MD -MP -MF .deps/pcap_filter.Tpo -c -o pcap_filter.o pcap_filter.c
mv -f .deps/pcap_filter.Tpo .deps/pcap_filter.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT wavfile_output_filter.o -MD -MP -MF .deps/wavfile_output_filter.Tpo -c -o wavfile_output_filter.o wavfile_output_filter.c
wavfile_output_filter.c: In function ‘wr_wavfile_output_filter_notify’:
wavfile_output_filter.c:115:21: warning: implicit declaration of function ‘timeval_increment’ [-Wimplicit-function-declaration]
                     timeval_increment(&state->end_time, frame->length_in_ms \* 1000);
                     ^
mv -f .deps/wavfile_output_filter.Tpo .deps/wavfile_output_filter.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT dummy_filter.o -MD -MP -MF .deps/dummy_filter.Tpo -c -o dummy_filter.o dummy_filter.c
mv -f .deps/dummy_filter.Tpo .deps/dummy_filter.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT independent_losses_filter.o -MD -MP -MF .deps/independent_losses_filter.Tpo -c -o independent_losses_filter.o independent_losses_filter.c
mv -f .deps/independent_losses_filter.Tpo .deps/independent_losses_filter.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT markov_losses_filter.o -MD -MP -MF .deps/markov_losses_filter.Tpo -c -o markov_losses_filter.o markov_losses_filter.c
mv -f .deps/markov_losses_filter.Tpo .deps/markov_losses_filter.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT uniform_delay_filter.o -MD -MP -MF .deps/uniform_delay_filter.Tpo -c -o uniform_delay_filter.o uniform_delay_filter.c
uniform_delay_filter.c: In function ‘wr_uniform_delay_filter_notify’:
uniform_delay_filter.c:65:13: warning: implicit declaration of function ‘timeval_increment’ [-Wimplicit-function-declaration]
             timeval_increment(&new_packet.lowlevel_timestamp, delay);
             ^
mv -f .deps/uniform_delay_filter.Tpo .deps/uniform_delay_filter.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT gamma_delay_filter.o -MD -MP -MF .deps/gamma_delay_filter.Tpo -c -o gamma_delay_filter.o gamma_delay_filter.c
gamma_delay_filter.c: In function ‘wr_gamma_delay_filter_notify’:
gamma_delay_filter.c:63:13: warning: implicit declaration of function ‘timeval_increment’ [-Wimplicit-function-declaration]
             timeval_increment(&new_packet.lowlevel_timestamp, delay);
             ^
mv -f .deps/gamma_delay_filter.Tpo .deps/gamma_delay_filter.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT log_filter.o -MD -MP -MF .deps/log_filter.Tpo -c -o log_filter.o log_filter.c
mv -f .deps/log_filter.Tpo .deps/log_filter.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT sipp_filter.o -MD -MP -MF .deps/sipp_filter.Tpo -c -o sipp_filter.o sipp_filter.c
mv -f .deps/sipp_filter.Tpo .deps/sipp_filter.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT sort_filter.o -MD -MP -MF .deps/sort_filter.Tpo -c -o sort_filter.o sort_filter.c
mv -f .deps/sort_filter.Tpo .deps/sort_filter.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT g711a_codec.o -MD -MP -MF .deps/g711a_codec.Tpo -c -o g711a_codec.o g711a_codec.c
mv -f .deps/g711a_codec.Tpo .deps/g711a_codec.Po
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT misc.o -MD -MP -MF .deps/misc.Tpo -c -o misc.o misc.c
mv -f .deps/misc.Tpo .deps/misc.Po
gcc  -g -O2   -o wav2rtp wav2rtp.o rtpmap.o options.o speex_codec.o dummy_codec.o gsm_codec.o g711u_codec.o g711.o in_cksum.o iniparser.o simclist.o com.o linpack.o ranlib.o rtpapi.o wavfile_filter.o pcap_filter.o wavfile_output_filter.o dummy_filter.o independent_losses_filter.o markov_losses_filter.o uniform_delay_filter.o gamma_delay_filter.o log_filter.o sipp_filter.o sort_filter.o g711a_codec.o misc.o  -lpcap -lspeex -lsndfile -lgsm -lm
make[2]: Leaving directory '/root/wav2rtp/wav2rtp-0.9.3/src'
Making all in conf
make[2]: Entering directory '/root/wav2rtp/wav2rtp-0.9.3/conf'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/wav2rtp/wav2rtp-0.9.3/conf'
Making all in doc
make[2]: Entering directory '/root/wav2rtp/wav2rtp-0.9.3/doc'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/wav2rtp/wav2rtp-0.9.3/doc'
make[2]: Entering directory '/root/wav2rtp/wav2rtp-0.9.3'
make[2]: Nothing to be done for 'all-am'.
make[2]: Leaving directory '/root/wav2rtp/wav2rtp-0.9.3'
make[1]: Leaving directory '/root/wav2rtp/wav2rtp-0.9.3'

**Comment by imankulov** [comment]
I'm sorry, but unfortunately the project is not maintained anymore. Of course, if you're courageous, you are more than welcome to fork it and fix the issue yourself.
