### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by ghost** [imankulov/wav2rtp#2]
gcc  -g -O2   -o wav2rtp wav2rtp.o rtpmap.o options.o speex_codec.o dummy_codec.o gsm_codec.o g711u_codec.o g711.o in_cksum.o iniparser.o simclist.o com.o linpack.o ranlib.o rtpapi.o wavfile_filter.o pcap_filter.o wavfile_output_filter.o dummy_filter.o independent_losses_filter.o markov_losses_filter.o uniform_delay_filter.o gamma_delay_filter.o log_filter.o sipp_filter.o sort_filter.o g711a_codec.o misc.o  -lpcap -lspeex -lsndfile -lgsm 
/usr/bin/ld: ranlib.o: неопределённая ссылка на символ «pow@@GLIBC_2.2.5»
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:589: recipe for target 'wav2rtp' failed

===
My hot fix: add **-lm** after gcc, i.e.:

gcc  -g -O2   -o wav2rtp wav2rtp.o rtpmap.o options.o speex_codec.o dummy_codec.o gsm_codec.o g711u_codec.o g711.o in_cksum.o iniparser.o simclist.o com.o linpack.o ranlib.o rtpapi.o wavfile_filter.o pcap_filter.o wavfile_output_filter.o dummy_filter.o independent_losses_filter.o markov_losses_filter.o uniform_delay_filter.o gamma_delay_filter.o log_filter.o sipp_filter.o sort_filter.o g711a_codec.o misc.o  -lpcap -lspeex -lsndfile -lgsm **-lm**

see: https://stackoverflow.com/questions/30013845/compiling-lib-x86-64-linux-gnu-libm-so-6-error-adding-symbols-dso-missing

**Comment by imankulov** [comment]
Thanks for the hint. I'm surprised people still find it useful.

I will keep the issue open, so that anyone who comes up with the same problem, can fix it the same way, but will not change the code to avoid leaving false impression that the project is alive 😅

**Comment by orgads** [comment]
This can be closed.

**Comment by willow1490** [comment]
@imankulov @orgads @sjthomason How to add 'lm' in Makefile to resolve the issue. Have tried to add lm  'LIBS = -lpcap -lspeex -lsndfile -lgsm  -lm' in the makefile, but i dont think it get reflected when i run the make command.

```
wav2rtp-0.9.3# make
make  all-recursive
make[1]: Entering directory '/workspace/wav2rtp-0.9.3'
Making all in src
make[2]: Entering directory '/workspace/wav2rtp-0.9.3/src'
gcc  -g -O2   -o wav2rtp wav2rtp.o rtpmap.o options.o speex_codec.o dummy_codec.o gsm_codec.o g711u_codec.o g711.o in_cksum.o iniparser.o simclist.o com.o linpack.o ranlib.o rtpapi.o wavfile_filter.o pcap_filter.o wavfile_output_filter.o dummy_filter.o independent_losses_filter.o markov_losses_filter.o uniform_delay_filter.o gamma_delay_filter.o log_filter.o sipp_filter.o sort_filter.o g711a_codec.o misc.o  -lpcap -lspeex -lsndfile -lgsm 
/usr/bin/ld: ranlib.o: undefined reference to symbol 'pow@@GLIBC_2.0'
//lib/i386-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:298: recipe for target 'wav2rtp' failed
make[2]: *** [wav2rtp] Error 1
make[2]: Leaving directory '/workspace/wav2rtp-0.9.3/src'
Makefile:252: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/workspace/wav2rtp-0.9.3'
Makefile:190: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by orgads** [comment]
@Malini1490 Did you checkout the latest version from github?
